### ISSUE TITLE
Quotes: make notices to not look ugly

### ISSUE THREAD

**Issue by Pato-desu** [PauseAI/pauseai-website#139]
It seems that we need to put lots of stuff in the notices of the pictures with BY licenses. At least the name, author, license and that was modified. Right now that would look really bad so we're using images without any type of rights.

We need to see if we can make all of that to not look bad, options:
- to make them smaller while still readable
- to put them outside the images and remove the feature to download them.

**Comment by Wituareard** [comment]
One could argue that a CC BY license note below the image implicitly requires everyone who downloads the image to also include credits when they repost it (and if they don't, that's not our fault) so that we wouldn't have to remove the download feature.

**Comment by Pato-desu** [comment]
Yeah, you're right, that sounds like the best solution
