### ISSUE TITLE
Color in CSS variable and on media page different from logo component

### ISSUE THREAD

**Issue by Wituareard** [PauseAI/pauseai-website#146]
The reason seems to be that the conversion from HEX/RGB to HSL is lossy. @joepio The color in the component is probably the correct one?

**Comment by Wituareard** [comment]
Okay I only just discovered that the logo doesn't adapt to the theme so it's probably fine if both the light and the dark theme color are different? But the media page needs to be adjusted.

**Comment by joepio** [comment]
Sorry not sure I follow. Which media page? The [/press](https://pauseai.info/press) page? It links to a google drive and a figma - I'd be confused if these are in some way different from the site logo.

The site logo is defined in a Svelte component which changes the pause and logo colors based on the theme:

<img width="363" alt="Screenshot 2024-04-08 at 09 29 11" src="https://github.com/PauseAI/pauseai-website/assets/2183313/fad6cd3d-c9e9-4ea6-80c1-0312432fd4fa">
<img width="405" alt="Screenshot 2024-04-08 at 09 29 07" src="https://github.com/PauseAI/pauseai-website/assets/2183313/b9a2be0a-82fe-4ee1-9511-11ce2d546718">
