### ISSUE TITLE
Add meeting to flyering guide

### ISSUE THREAD

**Issue by Wituareard** [PauseAI/pauseai-website#148]
See this Discord message: https://discord.com/channels/1100491867675709580/1100491868304846943/1227388501226557582

**Comment by Wituareard** [comment]
Additional idea: Physical sign-up form: https://discord.com/channels/1100491867675709580/1209542284048339027/1231629437171404880

**Comment by Pato-desu** [comment]
https://github.com/PauseAI/pauseai-website/commit/28af29541b4e201d208cb3616c0ede6281a09905
