### ISSUE TITLE
Add contact details (email?) to /teams

### ISSUE THREAD

**Issue by Wituareard** [PauseAI/pauseai-website#155]

**Comment by joepio** [comment]
I've heard people make the case against this for spam reasons. I'm personally more inclined to think it's worth it to make people more easily reachable.

**Comment by Wituareard** [comment]
Hm, the idea was that I don't really see the value in reading who is responsible for certain activities if there is no apparent way to reach them.

**Comment by Wituareard** [comment]
Resolved in 5cce3cd
