### ISSUE TITLE
Add "Head of AI Safety at US AI Safety Institute" to Paul Christiano

### ISSUE THREAD

**Issue by Wituareard** [PauseAI/pauseai-website#166]
...on /pdoom and /quotes. I couldn't find a way to make it fit into the layout.

- [x] /pdoom
- [x] /quotes

**Comment by Pato-desu** [comment]
https://github.com/PauseAI/pauseai-website/commit/a856e2af728d6710310219c577fe66010d285a5c

I'm not sure about what fitting are you talking about
