### ISSUE TITLE
Papers/ sources page

### ISSUE THREAD

**Issue by Pato-desu** [PauseAI/pauseai-website#175]
We could recompile all papers from the last one from Bengio and Hinton to more basic technical ones to a single page to give more credence to our general claims.

And/ or we could have a Sources page to redirect to it/ have the papers on it, the Polls page and the Quotes page.

What do you think?

**Comment by joepio** [comment]
I like the idea of bundling scientific literature!

**Comment by Pato-desu** [comment]
This may be useful https://airtable.com/appipV7kksvp3vK3Z/shrC6wDWhpOPdArT3/tblyor6zIK7Acjok0

**Comment by Pato-desu** [comment]
https://futureoflife.org/resource/introductory-resources-on-ai-risks/#toc-44245428-2
https://arkose.org/aisafety

These could also be added to specific claims that we make throught out the website, but I don't know where to start

**Comment by Pato-desu** [comment]
https://github.com/PauseAI/pauseai-website/commit/5c66ea7d66681e444a5d23997179e52301e6ec81 good enough I guess
